# manage logrotate
- name: nickhammond.logrotate
  version: 91d570f68c44261d2051a99a2b3c7d736306bf0d
- name: robertdebock.update_package_cache
- name: robertdebock.hostname
- name: robertdebock.git
- name: robertdebock.swap
- name: robertdebock.sysctl
- name: robertdebock.tune2fs
- name: robertdebock.diskspace
- name: robertdebock.maintenance
- name: robertdebock.openssh
- name: robertdebock.users
- name: robertdebock.common
- name: gantsign.keyboard
  version: 1.5.0
- name: jnv.unattended-upgrades
  version: v1.11.0
