---
- name: Converge
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    docker_in_docker: false
    machine_type: generic-x86-64

  tasks:
    - name: "Include hass role"
      include_role:
        name: "hass"
    - name: "Wait before running the test"  # give the supervisor time to launch all containers
      wait_for:
        timeout: 20
