---
- hosts: all
  tasks:
    - name: Make sure systemd-networkd is running
      ansible.builtin.systemd:
        state: started
        name: systemd-networkd
        enabled: true

    - name: Make sure systemd-networkd-wait-online is running
      ansible.builtin.systemd:
        state: started
        name: systemd-networkd-wait-online
        enabled: true
      when: not (ansible_distribution == 'Debian' and ansible_distribution_major_version == '11')

    - name: Remove old docker data
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      loop:
        - /var/lib/docker/runtimes/
        - /var/lib/docker/containers/
        - /var/lib/docker/network/
        - /var/lib/docker/volumes/
        - /var/lib/docker/tmp/
